{{- if .Values.global.atlasLogstash.enabled }}
{{- if .Values.logstashConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "logstash.fullname" . }}-config
  namespace: {{ template "logstash.namespace" . }}
  labels:
    app: "{{ template "logstash.fullname" . }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{- range $path, $config := .Values.logstashConfig }}
  {{ $path }}: |
{{ tpl $config $ | indent 4 -}}
{{- end -}}
{{- end -}}
{{- end -}}
