{{- if .Values.global.atlasLogstash.enabled }}
{{- if .Values.maxUnavailable }}
{{- if not (eq .Values.global.Deployment_Type "Lite") }}
{{- if .Capabilities.APIVersions.Has "policy/v1" -}}
apiVersion: policy/v1
{{- else}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: "{{ template "logstash.fullname" . }}-pdb"
  namespace: {{ template "logstash.namespace" . }}
  labels:
    app: "{{ template "logstash.fullname" . }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      app: "{{ template "logstash.fullname" . }}"
{{- end }}
{{- end -}}
{{- end -}}
