{{- if .Values.global.atlasLogstash.enabled }}
{{- if .Values.rbac.create -}}
{{- $fullName := include "logstash.fullname" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullName | quote }}
  namespace: {{ template "logstash.namespace" . }}
  labels:
    app: "{{ template "logstash.fullname" . }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
subjects:
  - kind: ServiceAccount
    name: "{{ template "logstash.serviceAccount" . }}"
    namespace: {{ template "logstash.namespace" . }}
roleRef:
  kind: Role
  name: {{ $fullName | quote }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
{{- end }}
