{{- if .Values.rbac.create -}}
{{- $fullName := include "elasticsearch.uname" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if eq .Values.rbac.serviceAccountName "" }}
  name: {{ $fullName | quote }}
  namespace: {{ .Values.Namespace }}
  {{- else }}
  name: {{ .Values.rbac.serviceAccountName | quote }}
  namespace: {{ .Values.Namespace }}
  {{- end }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    app: {{ $fullName | quote }}
{{- end -}}
