{{ if .Values.global.leangraph.dedicated.enabled }}
---
{{- $isAWSCloud := eq .Values.global.cloud "aws" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atlas-leangraph-elasticsearch-master
  namespace: {{ .Values.Namespace }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    app: "atlas-leangraph-elasticsearch-master"
  annotations:
    esMajorVersion: "7"
spec:
  serviceName: atlas-leangraph-elasticsearch-master-headless
  selector:
    matchLabels:
      app: "atlas-leangraph-elasticsearch-master"
  replicas: {{ default 3 .Values.replicas }}
  podManagementPolicy: {{ default "Parallel" .Values.podManagementPolicy }}
  updateStrategy:
    type: {{ default "RollingUpdate" .Values.updateStrategy }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: atlas-leangraph-elasticsearch-master
    {{- with .Values.persistence.annotations  }}
      annotations:
{{ toYaml . | indent 8 }}
    {{- end }}
    spec:
{{ toYaml .Values.volumeClaimTemplate | indent 6 }}
  {{- end }}
  template:
    metadata:
      name: "atlas-leangraph-elasticsearch-master"
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        app: "atlas-leangraph-elasticsearch-master"
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      {{- if .Values.schedulerName }}
      schedulerName: "{{ .Values.schedulerName }}"
      {{- end }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
        {{- if .Values.fsGroup }}
        fsGroup: {{ .Values.fsGroup }}
        {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- if or (eq .Values.antiAffinity "hard") (eq .Values.antiAffinity "soft") .Values.nodeAffinity }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      affinity:
      {{- end }}
      {{- $tierType := .Values.global.Tier_Type | default "" }}
      {{- if or (eq $tierType "Enterprise") (eq $tierType "") }}
      {{- if eq .Values.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: "atlas-leangraph-elasticsearch-master"
            topologyKey: {{ .Values.antiAffinityTopologyKey }}
      {{- else if eq .Values.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            podAffinityTerm:
              topologyKey: {{ .Values.antiAffinityTopologyKey }}
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - "atlas-leangraph-elasticsearch-master"
      {{- end }}
      {{- end }}
        nodeAffinity:
          {{- if eq .Values.global.Deployment_Type "Development" }}
          preferredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution | nindent 10 }}
          {{- else }}
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution | nindent 12 }}
          {{- end }}
      terminationGracePeriodSeconds: {{ default 120 .Values.terminationGracePeriod }}
      volumes:
        {{- range .Values.secretMounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
        {{- end }}
        {{- if .Values.esConfig }}
        - name: esconfig
          configMap:
            name: atlas-elasticsearch-master-config
        {{- end }}
        - name: elasticsearch-synonym-config
          configMap:
            name: elasticsearch-synonym-config
{{- if .Values.keystore }}
        - name: keystore
          emptyDir: {}
        {{- range .Values.keystore }}
        - name: keystore-{{ .secretName }}
          secret: {{ toYaml . | nindent 12 }}
        {{- end }}
{{ end }}
{{- if .Values.extraVolumes }}
      # Currently some extra blocks accept strings
      # to continue with backwards compatibility this is being kept
      # whilst also allowing for yaml to be specified too.
      {{- if eq "string" (printf "%T" .Values.extraVolumes) }}
{{ tpl .Values.extraVolumes . | indent 8 }}
      {{- else }}
{{ toYaml .Values.extraVolumes | indent 8 }}
      {{- end }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      initContainers:
      {{- if .Values.sysctlInitContainer.enabled }}
      - name: configure-sysctl
        securityContext:
          runAsUser: 0
          privileged: true
        {{- if and $isAWSCloud .Values.multiarch.enabled .Values.multiarch.image.elasticsearch }}
        image: {{ .Values.multiarch.image.elasticsearch }}
        {{- else }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        {{- end }}
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        command: ["sysctl", "-w", "vm.max_map_count={{ .Values.sysctlVmMaxMapCount}}"]
        resources:
{{ toYaml .Values.initResources | indent 10 }}
      {{- end }}
{{ if .Values.keystore }}
      - name: keystore
        {{- if and $isAWSCloud .Values.multiarch.enabled .Values.multiarch.image.elasticsearch }}
        image: {{ .Values.multiarch.image.elasticsearch }}
        {{- else }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        {{- end }}
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        command:
        - sh
        - -c
        - |
          #!/usr/bin/env bash
          set -euo pipefail

          for i in /tmp/keystoreSecrets/*/*; do
            key=$(basename $i)
            echo "Adding file $i to keystore key $key"
            elasticsearch-keystore add-file "$key" "$i"
          done

          # Add the bootstrap password since otherwise the Elasticsearch entrypoint tries to do this on startup
          if [ ! -z ${ELASTIC_PASSWORD+x} ]; then
            echo 'Adding env $ELASTIC_PASSWORD to keystore as key bootstrap.password'
            echo "$ELASTIC_PASSWORD" | elasticsearch-keystore add -x bootstrap.password
          fi

          cp -a /usr/share/elasticsearch/config/elasticsearch.keystore /tmp/keystore/
        env: {{ toYaml .Values.extraEnvs | nindent 10 }}
        resources: {{ toYaml .Values.initResources | nindent 10 }}
        volumeMounts:
          - name: keystore
            mountPath: /tmp/keystore
          {{- range .Values.keystore }}
          - name: keystore-{{ .secretName }}
            mountPath: /tmp/keystoreSecrets/{{ .secretName }}
          {{- end }}
{{ end }}
      {{- if .Values.extraInitContainers }}
{{ tpl .Values.extraInitContainers . | indent 6 }}
      {{- end }}
      containers:
      - name: "elasticsearch"
        securityContext:
{{ toYaml .Values.securityContext | indent 10 }}
        {{- if and $isAWSCloud .Values.multiarch.enabled .Values.multiarch.image.elasticsearch }}
        image: {{ .Values.multiarch.image.elasticsearch }}
        {{- else }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        {{- end }}
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
          exec:
            command:
              - sh
              - -c
              - |
                #!/usr/bin/env bash -e
                # If the node is starting up wait for the cluster to be ready (request params: '{{ .Values.clusterHealthCheckParams }}' )
                # Once it has started only check that the node itself is responding
                START_FILE=/tmp/.es_start_file

                http () {
                    local path="${1}"
                    if [ -n "${ELASTIC_USERNAME}" ] && [ -n "${ELASTIC_PASSWORD}" ]; then
                      BASIC_AUTH="-u ${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}"
                    else
                      BASIC_AUTH=''
                    fi
                    curl -XGET -s -k --fail ${BASIC_AUTH} {{ default "http" .Values.protocol }}://127.0.0.1:{{ default 9200 .Values.httpPort }}${path}
                }

                if [ -f "${START_FILE}" ]; then
                    echo 'Elasticsearch is already running, lets check the node is healthy and there are master nodes available'
                    http "/_cluster/health?timeout={{ .Values.healthCheckProbeTimeout }}"
                else
                    echo 'Waiting for elasticsearch cluster to become ready (request params: "{{ .Values.clusterHealthCheckParams }}" )'
                    if http "/_cluster/health?{{ .Values.clusterHealthCheckParams }}" ; then
                        touch ${START_FILE}
                        exit 0
                    else
                        echo 'Cluster is not yet ready (request params: "{{ .Values.clusterHealthCheckParams }}" )'
                        exit 1
                    fi
                fi
        ports:
        - name: http
          containerPort: {{ default 9200 .Values.httpPort }}
        - name: transport
          containerPort: {{ default 9300 .Values.transportPort }}
        resources:
{{- if eq .Values.global.Tier_Type "Enterprise" }}
{{ toYaml .Values.resources | indent 10 }}
{{- else if eq .Values.global.Tier_Type "Basic" }}
{{ toYaml .Values.resources_basic | indent 10 }}
{{- else if eq .Values.global.Tier_Type "Standard" }}
{{ toYaml .Values.resources_standard | indent 10 }}
{{- else }}
{{ toYaml .Values.resources | indent 10 }}
{{- end }}
        {{- if .Values.multitenant }}
        envFrom: {{ toYaml .Values.envFrom | nindent 10 }}
        {{- end }}
        env:
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: cluster.initial_master_nodes
            value: "atlas-leangraph-elasticsearch-master-0,atlas-leangraph-elasticsearch-master-1,atlas-leangraph-elasticsearch-master-2,"
          - name: discovery.seed_hosts
            value: "atlas-leangraph-elasticsearch-master-headless"
          - name: cluster.name
            value: "atlas-leangraph-elasticsearch"
          - name: cluster.max_shards_per_node
            value: "{{ default 4000 .Values.maxShardsPerNode }}"
          - name: network.host
            value: "{{ default "0.0.0.0" .Values.networkHost }}"
          - name: ES_JAVA_OPTS
            value: {{ .Values.esJavaOpts | quote }}
          - name: node.master
            value: "true"
          - name: node.ingest
            value: "true"
          - name: node.data
            value: "true"
{{- if .Values.extraEnvs }}
{{ toYaml .Values.extraEnvs | indent 10 }}
{{- end }}
        volumeMounts:
          {{- if .Values.persistence.enabled }}
          - name: "atlas-leangraph-elasticsearch-master"
            mountPath: /usr/share/elasticsearch/data
          {{- end }}
{{ if .Values.keystore }}
          - name: keystore
            mountPath: /usr/share/elasticsearch/config/elasticsearch.keystore
            subPath: elasticsearch.keystore
{{ end }}
          - name: elasticsearch-synonym-config
            mountPath: /usr/share/elasticsearch/config/synonym.txt
            subPath: synonym.txt
          {{- range .Values.secretMounts }}
          - name: {{ .name }}
            mountPath: {{ .path }}
            {{- if .subPath }}
            subPath: {{ .subPath }}
            {{- end }}
          {{- end }}
          {{- range $path, $config := .Values.esConfig }}
          - name: esconfig
            mountPath: /usr/share/elasticsearch/config/{{ $path }}
            subPath: {{ $path }}
          {{- end -}}
        {{- if .Values.extraVolumeMounts }}
        # Currently some extra blocks accept strings
        # to continue with backwards compatibility this is being kept
        # whilst also allowing for yaml to be specified too.
        {{- if eq "string" (printf "%T" .Values.extraVolumeMounts) }}
{{ tpl .Values.extraVolumeMounts . | indent 10 }}
        {{- else }}
{{ toYaml .Values.extraVolumeMounts | indent 10 }}
        {{- end }}
        {{- end }}
{{- if .Values.lifecycle }}
        lifecycle:
{{ toYaml .Values.lifecycle | indent 10 }}
{{- end }}
      {{- if .Values.extraContainers }}
      # Currently some extra blocks accept strings
      # to continue with backwards compatibility this is being kept
      # whilst also allowing for yaml to be specified too.
      {{- if eq "string" (printf "%T" .Values.extraContainers) }}
{{ tpl .Values.extraContainers . | indent 6 }}
      {{- else }}
{{ toYaml .Values.extraContainers | indent 6 }}
      {{- end }}
      {{- end }}
{{- end }}