{{- if or .Values.global.svcIsolation.enabled (or .Values.global.esIsolation.enabled .Values.global.globalSvcIsolation.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: atlas-read-logback-config
  namespace: {{ .Values.Namespace  }}
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  atlas-logback.xml: |
      <?xml version="1.0" encoding="UTF-8" ?>
      <!--
        ~ Licensed to the Apache Software Foundation (ASF) under one
        ~ or more contributor license agreements.  See the NOTICE file
        ~ distributed with this work for additional information
        ~ regarding copyright ownership.  The ASF licenses this file
        ~ to you under the Apache License, Version 2.0 (the
        ~ "License"); you may not use this file except in compliance
        ~ with the License.  You may obtain a copy of the License at
        ~
        ~     http://www.apache.org/licenses/LICENSE-2.0
        ~
        ~ Unless required by applicable law or agreed to in writing, software
        ~ distributed under the License is distributed on an "AS IS" BASIS,
        ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        ~ See the License for the specific language governing permissions and
        ~ limitations under the License.
        -->

      <configuration>
          <appender name="console" class="ch.qos.logback.core.ConsoleAppender">
              <param name="Target" value="System.out"/>
              <encoder>
                  <pattern>
                      logback: %d %-5p - atlas-application - [%t:%X{context-key}] - traceId:[%X{trace_id}]  ~ %m \(%C{1}:%L\)%n
                  </pattern>
              </encoder>
              <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
                  <level>INFO</level>
              </filter>
          </appender>

          <appender name="OpenTelemetry"
                    class="io.opentelemetry.instrumentation.logback.appender.v1_0.OpenTelemetryAppender">
              <!-- Additional capture options -->
              <captureExperimentalAttributes>true</captureExperimentalAttributes>
              <captureMdcAttributes>*</captureMdcAttributes>
              <captureLoggerContext>true</captureLoggerContext>
              <captureKeyValuePairAttributes>true</captureKeyValuePairAttributes>
          </appender>

          <appender name="consoleAudit" class="ch.qos.logback.core.ConsoleAppender">
              <param name="Target" value="System.out"/>
              <filter class="org.apache.atlas.web.filters.MDCFilter">
                  <mdcKey>filter</mdcKey>
                  <mdcValue>atlas-audit</mdcValue>
              </filter>
              <encoder>
                  <pattern>
                      logback: %d %-5p - atlas-audit - [%t:%X{context-key}] - X-Atlan-Request-Id:[%X{X-Atlan-Request-Id}] - traceId:[%X{trace_id}]  ~ %m \(%C{1}:%L\)%n
                  </pattern>
              </encoder>
              <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
                  <level>INFO</level>
              </filter>
          </appender>

          <appender name="consoleAuthAudit" class="ch.qos.logback.core.ConsoleAppender">
              <param name="Target" value="System.out"/>
              <filter class="org.apache.atlas.web.filters.MDCFilter">
                  <mdcKey>filter</mdcKey>
                  <mdcValue>atlas-auth-audit</mdcValue>
              </filter>
              <encoder>
                  <pattern>
                      logback: %d %-5p - atlas-auth-audit - [%t:%X{context-key}] - X-Atlan-Request-Id:[%X{X-Atlan-Request-Id}] - traceId:[%X{trace_id}]  ~ %m \(%C{1}:%L\)%n
                  </pattern>
              </encoder>
              <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
                  <level>INFO</level>
              </filter>
          </appender>

          <appender name="consoleAtlas" class="ch.qos.logback.core.ConsoleAppender">
              <param name="Target" value="System.out"/>
              <filter class="org.apache.atlas.web.filters.MDCFilter">
                  <mdcKey>filter</mdcKey>
                  <mdcValue>atlas-application</mdcValue>
              </filter>
              <encoder>
                  <pattern>
                      logback: %d %-5p - atlas-application - [%t:%X{context-key}] - X-Atlan-Request-Id:[%X{X-Atlan-Request-Id}] - traceId:[%X{trace_id}]   ~ %m \(%C{1}:%L\)%n
                  </pattern>
              </encoder>
              <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
                  <level>INFO</level>
              </filter>
          </appender>

          <appender name="consolePerf" class="ch.qos.logback.core.ConsoleAppender">
              <param name="Target" value="System.out"/>
              <filter class="org.apache.atlas.web.filters.MDCFilter">
                  <mdcKey>filter</mdcKey>
                  <mdcValue>atlas-perf</mdcValue>
              </filter>
              <encoder>
                  <pattern>
                      logback: %d %-5p - atlas-perf - [%t:%X{context-key}] - X-Atlan-Request-Id:[%X{X-Atlan-Request-Id}] - traceId:[%X{trace_id}]  ~ %m \(%C{1}:%L\)%n
                  </pattern>
              </encoder>
              <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
                  <level>INFO</level>
              </filter>
          </appender>

          <appender name="consoleRanger" class="ch.qos.logback.core.ConsoleAppender">
              <param name="Target" value="System.out"/>
              <filter class="org.apache.atlas.web.filters.MDCFilter">
                  <mdcKey>filter</mdcKey>
                  <mdcValue>atlas-ranger</mdcValue>
              </filter>
              <encoder>
                  <pattern>
                      logback: %d %-5p - atlas-application - [%t:%X{context-key}] - X-Atlan-Request-Id:[%X{X-Atlan-Request-Id}] - traceId:[%X{trace_id}] ~ %m \(%C{1}:%L\)%n
                  </pattern>
              </encoder>
              <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
                  <level>INFO</level>
              </filter>
          </appender>

          <appender name="consoleMetrics" class="ch.qos.logback.core.ConsoleAppender">
              <param name="Target" value="System.out"/>
              <filter class="org.apache.atlas.web.filters.MDCFilter">
                  <mdcKey>filter</mdcKey>
                  <mdcValue>atlas-metrics</mdcValue>
              </filter>
              <encoder>
                  <pattern>
                      logback: %d %-5p - atlas-metrics - [%t:%X{context-key}] - X-Atlan-Request-Id:[%X{X-Atlan-Request-Id}] - traceId:[%X{trace_id}]  ~ %m \(%C{1}:%L\)%n
                  </pattern>
              </encoder>
              <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
                  <level>INFO</level>
              </filter>
          </appender>

          <appender name="consoleTasks" class="ch.qos.logback.core.ConsoleAppender">
              <param name="Target" value="System.out"/>
              <filter class="org.apache.atlas.web.filters.MDCFilter">
                  <mdcKey>filter</mdcKey>
                  <mdcValue>atlas-tasks</mdcValue>
              </filter>
              <encoder>
                  <pattern>
                      logback: %d %-5p - atlas-application - [%t:%X{context-key}] - X-Atlan-Request-Id:[%X{X-Atlan-Request-Id}] - traceId:[%X{trace_id}]  ~ %m \(%C{1}:%L\)%n
                  </pattern>
              </encoder>
              <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
                  <level>INFO</level>
              </filter>
          </appender>

          <logger name="org.apache.atlas.auth.perf" additivity="false" level="OFF">
              <appender-ref ref="console"/>
              <appender-ref ref="OpenTelemetry"/>
          </logger>


          <logger name="AUTH_AUDIT" additivity="false" level="info">
              <appender-ref ref="consoleAuthAudit"/>
              <appender-ref ref="OpenTelemetry"/>
          </logger>

          <!-- Authz loggers End -->

          <logger name="org.apache.atlas.perf" additivity="false" level="debug">
              <appender-ref ref="consolePerf"/>
              <appender-ref ref="OpenTelemetry"/>
          </logger>

          <logger name="org.apache.atlas" additivity="false" level="info">
              <appender-ref ref="consoleAtlas"/>
              <appender-ref ref="OpenTelemetry"/>
          </logger>

          <logger name="org.apache.ranger" additivity="false" level="warn">
              <appender-ref ref="consoleRanger"/>
              <appender-ref ref="OpenTelemetry"/>
          </logger>

          <logger name="org.janusgraph" additivity="false" level="warn">
              <appender-ref ref="console"/>
              <appender-ref ref="OpenTelemetry"/>
          </logger>

          <logger name="org.springframework" additivity="false" level="warn">
              <appender-ref ref="console"/>
              <appender-ref ref="OpenTelemetry"/>
          </logger>

          <logger name="org.eclipse" additivity="false" level="warn">
              <appender-ref ref="console"/>
              <appender-ref ref="OpenTelemetry"/>
          </logger>

          <logger name="com.sun.jersey" additivity="false" level="warn">
              <appender-ref ref="console"/>
              <appender-ref ref="OpenTelemetry"/>
          </logger>

          <!-- to avoid logs - The configuration log.flush.interval.messages = 1 was supplied but isn't a known config -->
          <logger name="org.apache.kafka.common.config.AbstractConfig" additivity="false" level="error">
              <appender-ref ref="console"/>
              <appender-ref ref="OpenTelemetry"/>
          </logger>

          <logger name="AUDIT" additivity="false" level="info">
              <appender-ref ref="consoleAudit"/>
              <appender-ref ref="OpenTelemetry"/>
          </logger>

          <logger name="LARGE_MESSAGES" additivity="false" level="warn">
              <appender-ref ref="console"/>
              <appender-ref ref="OpenTelemetry"/>
          </logger>

          <logger name="METRICS" additivity="false" level="debug">
              <appender-ref ref="consoleMetrics"/>
              <appender-ref ref="OpenTelemetry"/>
          </logger>

          <logger name="FAILED" additivity="false" level="info">
              <appender-ref ref="console"/>
              <appender-ref ref="OpenTelemetry"/>
          </logger>

          <logger name="TASKS" additivity="false" level="info">
              <appender-ref ref="consoleTasks"/>
              <appender-ref ref="OpenTelemetry"/>
          </logger>

          <root level="INFO">
              <appender-ref ref="OpenTelemetry"/>
              <appender-ref ref="console"/>
          </root>
      </configuration>
{{- end }}
