{{- if or .Values.global.svcIsolation.enabled (or .Values.global.esIsolation.enabled .Values.global.globalSvcIsolation.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.atlas.serviceAccount.name }}
  namespace: {{ .Values.Namespace }}
  {{- with .Values.atlas.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
automountServiceAccountToken: {{ .Values.atlas.serviceAccount.automountServiceAccountToken }}
{{- end }}

