apiVersion: v1
kind: ConfigMap
metadata:
  name: create-atlas-keycloak-config-cm
  namespace: {{ .Values.Namespace }}
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  create-atlas-keycloak-config.sh: |
    cat <<EOF > /opt/apache-atlas/conf/keycloak.json
    {
        "realm": "KEYCLOAK_REALM",
        "auth-server-url": "AUTH_SERVER_URL",
        "ssl-required": "none",
        "resource": "KEYCLOAK_CLIENT_ID",
        "public-client": false,
        "confidential-port": 80,
        "principal-attribute": "preferred_username",
        "autodetect-bearer-only": true,
        "credentials": {
          "secret": "KEYCLOAK_CLIENT_SECRET"
        }
    }
    EOF
    sed -i "s|KEYCLOAK_REALM|$KEYCLOAK_REALM|g" "/opt/apache-atlas/conf/keycloak.json"
    sed -i "s|AUTH_SERVER_URL|$AUTH_SERVER_URL|g" "/opt/apache-atlas/conf/keycloak.json"
    sed -i "s|KEYCLOAK_CLIENT_ID|$KEYCLOAK_CLIENT_ID|g" "/opt/apache-atlas/conf/keycloak.json"
    sed -i "s|KEYCLOAK_CLIENT_SECRET|$KEYCLOAK_CLIENT_SECRET|g" "/opt/apache-atlas/conf/keycloak.json"
    echo "Keycloak Config Created"
