{{- if .Values.atlas.ingress.enabled -}}
{{- if eq .Values.atlas.Deployment_Type "Development" -}}
{{- $ingressApiIsStable := eq (include "atlas.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "atlas.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "atlas.ingress.supportsPathType" .) "true" -}}
{{- $servicePort := .Values.atlas.service.port -}}
{{- $ingressPath := .Values.atlas.ingress.path -}}
{{- $ingressPathType := .Values.atlas.ingress.pathType -}}
{{- $extraPaths := .Values.atlas.ingress.extraPaths -}}
apiVersion: {{ include "atlas.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: atlas-atlas
  namespace: {{ .Values.Namespace  }}
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.atlas.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.atlas.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if and $ingressSupportsIngressClassName .Values.atlas.ingress.ingressClassName }}
  ingressClassName: {{ .Values.atlas.ingress.ingressClassName }}
  {{- end -}}
{{- if .Values.atlas.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.atlas.ingress.tls.host }}
      secretName: {{ .Values.atlas.ingress.tls.secretName }}
{{- end }}
  rules:
  {{- if .Values.atlas.ingress.hosts  }}
  {{- range .Values.atlas.ingress.hosts }}
    - host: {{ tpl . $}}
      http:
        paths:
{{- if $extraPaths }}
{{ toYaml $extraPaths | indent 10 }}
{{- end }}
          - path: {{ $ingressPath }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: atlas-ui-service
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: atlas-ui-service
              servicePort: {{ $servicePort }}
              {{- end }}
  {{- end }}
  {{- else }}
    - http:
        paths:
          - backend:
              {{- if $ingressApiIsStable }}
              service:
                name: atlas-ui-service
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: atlas-ui-service
              servicePort: {{ $servicePort }}
              {{- end }}
            {{- if $ingressPath }}
            path: {{ $ingressPath }}
            {{- end }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
  {{- end -}}
{{- end }}
{{- end }}